site_name: 又拍云文档中心
site_url: https://docs.upyun.com/
repo_url: https://github.com/upyun/docs/
docs_dir: sources
theme_dir: theme/updocs
copyright: Copyright &copy; 2016, 又拍云

pages:

- '文档首页': 'index.md'
- '开发指南':
    - '开发者指南': 'guide/index.md'
    - 'REST API 简易指南(PHP)': 'guide/php_rest_guide.md'
- 'CDN 文档':
    - '基础特性': 'cdn/index.md'
    - '高级特性': 'cdn/feature.md'
- '直播文档':
    - '直播文档': 'live/index.md'
- 'API 文档':
    - 'API 概览': 'api/index.md'
    - 'HTTP REST API': 'api/rest_api.md'
    - 'HTTP FORM API': 'api/form_api.md'
    - '分块上传': 'api/multipart_upload.md'
    - '缓存刷新': 'api/purge.md'
    - 'API 错误码表': 'api/errno.md'
    - '图片处理参数（旧）': 'api/old_thumb.md'
    - '视频处理（旧）': 'api/av_pretreatment.md'
    - '移动流量API': 'mobile-stats/index.md'
- '云处理文档':
    - '云处理概述': 'cloud/index.md'
    - '图片处理': 'cloud/image.md'
    - '音视频处理': 'cloud/av.md'
    - '压缩解压缩': 'cloud/unzip.md'
    - '异步文件拉取': 'cloud/spider.md'
    - '附件': 'cloud/attachment.md'
- '资源下载':
    - '资源下载': 'download/index.md'
- '常见问题':
    - '常见问题': 'faq/index.md'

# Add permalink for sharing
markdown_extensions:
    - toc:
        permalink: True
