site_name: 又拍云文档中心
site_url: https://docs.upyun.com/
repo_url: https://github.com/upyun/docs/
docs_dir: sources
theme_dir: theme/updocs
copyright: Copyright &copy; 2016, 又拍云

pages:

- '文档首页': 'index.md'
- '开发指南':
    - '开发者指南': 'guide/index.md'
    - 'REST API 简易指南(PHP)': 'guide/php_rest_guide.md'
- 'CDN 文档':
    - '产品简介': 'cdn/index.md'
    - '快速入门': 'cdn/guide.md'
    - '基础设置': 'cdn/basic.md'
    - '高级设置': 'cdn/advanced.md'
    - '证书服务': 'cdn/ssl.md'
    - '辅助工具': 'cdn/tools.md'
    - '常见问题': 'cdn/faq.md'
- '直播文档':
    - '直播文档': 'live/index.md'
- '云存储文档':
    - '产品简介': 'api/index.md'
    - '快速入门': 'api/quick_start.md'
    - '开发者指南': 'api/developer_guide.md'
    - '认证鉴权': 'api/authorization.md'
    - 'REST API': 'api/rest_api.md'
    - 'FORM API': 'api/form_api.md'
    - '开发者工具': 'api/developer_tools.md'
    - '分块上传（旧）': 'api/multipart_upload.md'
    - 'API 错误码表': 'api/errno.md'
    - '缓存刷新': 'api/purge.md'
    - '移动流量': 'mobile-stats/index.md'
- '云处理文档':
    - '产品简介': 'cloud/index.md'
    - '图片处理': 'cloud/image.md'
    - '认证鉴权': 'cloud/authorization.md'
    - '音视频处理': 'cloud/av.md'
    - '内容审核': 'cloud/audit.md'
    - '人脸识别': 'cloud/face_detect.md'
    - '压缩解压缩': 'cloud/unzip.md'
    - '文件拉取': 'cloud/spider.md'
    - '音视频处理（旧）': 'cloud/av_pretreatment.md'
- '资源下载':
    - '资源下载': 'download/index.md'
- '常见问题':
    - '常见问题': 'faq/index.md'

# Add permalink for sharing
markdown_extensions:
    - toc:
        permalink: True
